### ISSUE TITLE
Does not match "fulfillment_messages" format

### ISSUE THREAD

**Issue by owenbrown** [dialogflow/fulfillment-webhook-json#3]
When users create static rich responses for Action on Google in the DialogFlow console, these messages are translated into JSON and passed to the fulfillment webhook.

The format sent to the fulfillment webhook is completely different than what is displayed here, which is also completely different than what is displayed in the documentation (https://developers.google.com/actions/dialogflow/webhook).

If we can't get a Python SDK for connecting to Actions on Google through DialogFlow, can we at least get consistent advice on the JSON format to return? Other platform, such as Facebook Messenger, provide simple, clear documentation on the format.

**Comment by mattcarrollcode** [comment]
What inconsistency are you seeing between this repo and https://developers.google.com/actions/dialogflow/webhook?
