### ISSUE TITLE
Trailing comma in request.json

### ISSUE THREAD

**Issue by zugaldia** [dialogflow/fulfillment-webhook-json#4]
I'm trying to use the files in this repo as test fixtures and I'm hitting an issue parsing [`requests/v2/request.json`](https://github.com/dialogflow/fulfillment-webhook-json/blob/master/requests/v2/request.json#L25). The following trailing comma is tripping my Json decoder (Jackson) as it goes against the JSON spec:

```
"parameters": {
  "param": "param value",
}
```

The error is:

```
com.fasterxml.jackson.core.JsonParseException: Unexpected character ('}' (code 125)): was expecting double-quote to start field name
```

Removing the comma fixes the issue.

Otherwise, thanks team for providing these files. It's great to have them as a resource while building a webhook.

**Comment by findzaatar** [comment]
Fixed
