### ISSUE TITLE
Access-Control-Allow-Origin

### ISSUE THREAD

**Issue by sushantkumarswain** [dialogflow/fulfillment-webhook-json#9]
Failed to load.... No 'Access-Control-Allow-Origin' header is present on the requested resource.Therefore not allowed access. The response had HTTP status code 415.

**Comment by sushantkumarswain** [comment]
When I check with API through Ajax post request ,it is throwing an error : Failed to load resources:ERR_CERT_COMMON_NAME_INVALID error ) when accessing remote HTTPS webpage.

Is there anyone who can help me how to get rid of the errors and receive the data I need for my application?

**Comment by findzaatar** [comment]
@sushantkumarswain You're running into a CORS issue, you can read more on this [here](https://stackoverflow.com/questions/20035101/why-does-my-javascript-get-a-no-access-control-allow-origin-header-is-present).
